type Query {
    readOneUser(userId: ID!): UserReadOnePayload!
    readUserList: [UserReadOnePayload!]
}

type Mutation {
    signUpUser(input: UserSignUpInput!): UserSignUpPayload!
    editUser(input: UserEditInput!): UserEditPayload!
    deleteUser(userId: ID!): ID!
}
type UserReadOnePayload {
    id: ID!
    name: String!
}

type UserSignUpPayload {
    id: ID!
    name: String!
}

type UserEditPayload {
    id: ID!
    name: String!
}

input UserSignUpInput {
    name: String!
}

input UserEditInput {
    id: ID!
    name: String!
}
